---
# tasks file for deb_sql
---
 - name: Install the MySQL packages
   apt: name={{ item }} state=latest update_cache=yes
   loop:
     - mysql-server
     - mysql-client
     - python3-mysqldb
     - libmysqlclient-dev

 - name: Copy the configuration file (my.cnf)
   template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
   notify:
     - restart mysql

 - name: Copy the root credentials as .my.cnf file
   template: src=root.cnf.j2 dest=~/.my.cnf mode=0600

 - name: Update MySQL root password for all root accounts
   mysql_user: name=root host={{ item }} password={{ mysql_root_pass }} state=present
   loop:
     - "{{ ansible_hostname }}"
     - 127.0.0.1
     - ::1
     - localhost



 - name: Ensure Anonymous user(s) are not in the database
   mysql_user: name='' host={{ item }} state=absent
   with_items:
     - localhost
     - "{{ ansible_hostname }}"

 - name: Remove the test database
   mysql_db: name=test state=absent
   notify:
     - restart mysql