- name: restart nginx Ubuntu
  ansible.builtin.service: name=nginx state=restarted enabled=yes
  when: ansible_os_family=="Debian"
- name: restart nginx Centos
  ansible.builtin.service: name=nginx state=restarted enabled=yes
  when: ansible_os_family=="RedHat"